name: Sonatype Workflow Defaults
on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    # Perform an evaluation
    - name: Run evaluate action
      id: evaluate
      uses: sonatype/actions/evaluate@v1
      with:
        iq-server-url: ${{ vars.SONATYPE_IQ_URL }}
        username: ${{ secrets.SONATYPE_IQ_USERNAME }}
        password: ${{ secrets.SONATYPE_IQ_PASSWORD }}
        application-id: sonatype-field-workshop-default
        scan-targets: target/struts2-rest-showcase.war
        debug: true
        # Print out the results
    - name: Log evaluate action output
      run: echo "${{ steps.evaluate.outputs.scan-id }} ${{ steps.evaluate.outputs.report-url }}"
    - name: Dump evaluate outputs
      run: echo "${{ steps.evaluate.outputs }}"
      
    - name: Fetch SBOM
      uses: sonatype/actions/fetch-sbom@v1
      if: ( success() || failure() ) && steps.evaluate.outputs.scan-id
      with:
        iq-server-url: ${{ secrets.SONATYPE_IQ_URL }}
        username: ${{ secrets.SONATYPE_IQ_USERNAME }}
        password: ${{ secrets.SONATYPE_IQ_PASSWORD }}
        application-id: sonatype-field-workshop-default
        scan-id: ${{ steps.evaluate.outputs.scan-id }}
        sbom-standard: cyclonedx
        sbom-version: 1.5
        sbom-format: json
        artifact-name: cylonedx-bom
